/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Verify the API is running
         */
        get: operations["app.routes.health.health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Github Issues
         * @description Returns list of github issues for a given repository
         */
        get: operations["app.routes.issues.issues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devin/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Devin analysis
         * @description Creates a Devin session to analyze a GitHub issue
         */
        post: operations["app.routes.devin.analyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devin/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get analysis status
         * @description Returns the current status and results of a Devin analysis
         */
        get: operations["app.routes.devin.get_analysis_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devin/fix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Devin fix
         * @description Creates a Devin session to implement a fix and create a PR
         */
        post: operations["app.routes.devin.fix_issue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devin/fix-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get fix status
         * @description Returns the current status of a Devin fix session
         */
        get: operations["app.routes.devin.get_fix_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthOut: {
            message: string;
            status: string;
        };
        Issue: {
            issue_id: number;
            issue_title: string;
            body?: string;
            state: string;
            author: string;
            author_avatar?: string;
            labels?: components["schemas"]["Label"][];
            created_at: string;
            comment_count: number;
        };
        Label: {
            name: string;
            color: string;
        };
        AnalyzeRequest: {
            /** @description GitHub repository URL */
            github_url: string;
            /** @description Issue number */
            issue_id: number;
            /** @description Issue title */
            issue_title: string;
        };
        AnalyzeResponse: {
            session_id: string;
            status: string;
            devin_url?: string;
        };
        AnalysisResult: {
            github_url: string;
            issue_id: number;
            session_id?: string;
            status: string;
            plan?: string | null;
            confidence_score?: number | null;
            devin_url?: string | null;
            created_at?: string | null;
            updated_at?: string | null;
        };
        FixRequest: {
            /** @description GitHub repository URL */
            github_url: string;
            /** @description Issue number */
            issue_id: number;
            /** @description Issue title */
            issue_title: string;
            /** @description Implementation plan from analysis */
            plan: string;
        };
        FixResponse: {
            session_id: string;
            status: string;
            devin_url?: string;
        };
        FixStatusResult: {
            github_url: string;
            issue_id: number;
            fix_status?: string | null;
            fix_session_id?: string | null;
            fix_devin_url?: string | null;
            pr_url?: string | null;
        };
        ErrorResponse: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "app.routes.health.health_check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    "app.routes.issues.issues": {
        parameters: {
            query: {
                /** @description GitHub repository URL (e.g. https://github.com/owner/repo) */
                github_url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"][];
                };
            };
        };
    };
    "app.routes.devin.analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Analysis started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "app.routes.devin.get_analysis_status": {
        parameters: {
            query: {
                /** @description GitHub repository URL */
                github_url: string;
                /** @description Issue number */
                issue_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analysis found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Analysis not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "app.routes.devin.fix_issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FixRequest"];
            };
        };
        responses: {
            /** @description Fix started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "app.routes.devin.get_fix_status": {
        parameters: {
            query: {
                /** @description GitHub repository URL */
                github_url: string;
                /** @description Issue number */
                issue_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fix status found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixStatusResult"];
                };
            };
            /** @description Fix not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
